name: Generate Snake

# Définit les événements qui déclenchent l'action
on:
  schedule:
    # Exécute l'action toutes les 6 heures
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permet d'exécuter l'action manuellement depuis l'onglet Actions

jobs:
  build:
    # Type d'environnement d'exécution
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code dans le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape pour générer le GIF et le SVG du serpent
      - name: Generate the snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mishmanners # Remplacez par votre nom d'utilisateur GitHub
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Affiche l'état du dépôt git (utile pour le débogage)
      - name: Show git status
        run: git status

      # Étape pour pousser les modifications sur la branche spécifiée
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master # Changez en 'main' si c'est votre branche par défaut
          force: true

      # Étape pour déployer les fichiers générés sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output # Branche où les fichiers seront poussés
          build_dir: dist # Dossier contenant les fichiers générés
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Utilisation du token GitHub pour l'authentification
